name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install
      - name: Run tests
        run: mvn test
      - name: Build Docker image
        run: docker build -t iot-data-processing:latest .
      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: iot-data-processing-image
          path: '**/target/*.jar'
      # Add deployment steps for your cloud provider below
      # - name: Deploy to Kubernetes/AWS/Azure/GCP
      #   run: ...